###########################################################################
### Application 설정
###########################################################################
application:

  cors:
    allowed-origin:
      - http://nas.hooni.co.kr

  frontend:
    scheme: http
    host: nas.hooni.co.kr
    port: 80
  gateway: http://nas-gateway.hooni.co.kr

###########################################################################
### server 설정
###########################################################################
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: lax
  error:
    whitelabel:
      enabled: false

###########################################################################
### Spring 설정
###########################################################################
spring:
  application:
    root: gateway
    name: gateway-nas

  ### Redis 설정 ###
  data:
    redis:
      host: 192.168.45.170
      port: 6379
      username: hooni
      password: ENC(va2SQtNj/JN0yL4tXoiFvy1/zppdnE5nhZl4GTdKZEOg1chE+H5LYyMkLD5kkgzi)

  ### Cloud 설정 ###
  webflux:
    base-path:
  cloud:
    gateway:
      filter:
        retry:
          enabled: false

  ### Datasource 설정 ###
  r2dbc:
    url: ENC(Z98CeX+FT1EiHYE6Et0UAa1eH7+4clLUPrbEtS+iDOMSMN8i7bGLrLvNUzc3A4T6KXL1OtlkG93cyh8PRUr/8my8QhUP4ueKSV+Agy+iFZg=)
    username: ENC(pB9tWjIcgj6jMYSl/rbw2RR9hbIl8Erz5yTcKFRD+KIKIjNenzjD3wmiX6ACSYHw)
    password: ENC(JoC36RZPrti8Hs6JGp9Yy7OR+YuOPVqKdbiNRpyW1q+rjGXL6qXAUExSEGaAYg+E)

  security:
    access:
      nologin:
        - /auth/login
        - /auth/logout
        - /auth/session
        - /auth/refresh
        - /auth/register
        - /auth/existsUserId

###########################################################################
### Router data 설정
###########################################################################
routers:
  defaults:
    nas-api:
      context: nas
      scheme: http
      host: nas-api-service.nas.svc
      port: 80

###########################################################################
### Jasypt 설정
###########################################################################
jasypt:
  encryptor:
    password: ${ENCRYPTOR_PROFILE}

###########################################################################
### jwt 설정
###########################################################################
jwt:
  secretkey: ENC(fkLWNwMEhnest9nhBCWy4uxCHDBLzKRzyzuLOwTnicJrEpH3ZlRImo2/6ILWwq6lQWS9CQzfutcCWIjJcKaZG/r/qDqY578FMythF1hx5oV9vZCfYmKeppOU49+dOjP5)